In [0]:
# !pip install category-encoders

import numpy as np
import pandas as pd
import category_encoders as ce
from sklearn.preprocessing import OneHotEncoder, StandardScaler 
import matplotlib.pyplot as plt

In [0]:
file_path = '/content/drive/My Drive/Colab Notebooks/DataVisualisation/players_20_temp.csv'

In [0]:
df = pd.read_csv(file_path)
df.head()

                                          player_url  ...  nation_jersey_number
0  https://sofifa.com/player/158023/lionel-messi/...  ...                   NaN
1  https://sofifa.com/player/20801/c-ronaldo-dos-...  ...                   7.0
2  https://sofifa.com/player/190871/neymar-da-sil...  ...                  10.0
3  https://sofifa.com/player/200389/jan-oblak/20/...  ...                   1.0
4  https://sofifa.com/player/183277/eden-hazard/2...  ...                  10.0

[5 rows x 32 columns]

In [0]:
df = pd.read_csv(file_path)
df['wage_eur'] = df['wage_eur'].replace(0, pd.NA)
df['value_eur'] = df['value_eur'].replace(0, pd.NA)
df['player_positions'] = df['player_positions'].str.split(', ')
# df['player_positions'] = df['player_positions'].str.split(', ',expand=True) # to choose the first position only
df[['att_work_rate','def_work_rate']] = df['work_rate'].str.split('/', expand=True)
df['growth'] = df['potential'] - df['overall']
df.head(10)

                                          player_url  age  ...  def_work_rate  growth
0  https://sofifa.com/player/158023/lionel-messi/...   32  ...            Low       0
1  https://sofifa.com/player/20801/c-ronaldo-dos-...   34  ...            Low       0
2  https://sofifa.com/player/190871/neymar-da-sil...   27  ...         Medium       0
3  https://sofifa.com/player/200389/jan-oblak/20/...   26  ...         Medium       2
4  https://sofifa.com/player/183277/eden-hazard/2...   28  ...         Medium       0
5  https://sofifa.com/player/192985/kevin-de-bruy...   28  ...           High       0
6  https://sofifa.com/player/192448/marc-andre-te...   27  ...         Medium       3
7  https://sofifa.com/player/203376/virgil-van-di...   27  ...         Medium       1
8  https://sofifa.com/player/177003/luka-modric/2...   33  ...           High       0
9  https://sofifa.com/player/209331/mohamed-salah...   27  ...         Medium       0

[10 rows x 35 columns]

In [0]:
df.isnull().sum()

player_url                      0
age                             0
height_cm                       0
weight_kg                       0
nationality                     0
club                            0
overall                         0
potential                       0
value_eur                     250
wage_eur                      240
player_positions                0
preferred_foot                  0
international_reputation        0
weak_foot                       0
skill_moves                     0
work_rate                       0
release_clause_eur           1298
team_jersey_number            240
contract_valid_until          240
pace                         2036
shooting                     2036
passing                      2036
dribbling                    2036
defending                    2036
physic                       2036
gk_diving                   16242
gk_handling                 16242
gk_kicking                  16242
gk_reflexes                 16242
gk_speed                    16242
gk_positioning              16242
nation_jersey_number        17152
att_work_rate                   0
def_work_rate                   0
growth                          0
dtype: int64

In [0]:
# fill NaNs

df = df.sort_values(["overall", "age"], ascending = (False, True))
df['wage_eur'] = df['wage_eur'].ffill()
df['value_eur'] = df['value_eur'].ffill()
df['release_clause_eur'] = df['release_clause_eur'].ffill()
# df['release_clause_eur'].fillna(df['release_clause_eur'].mean(), inplace=True)
df['contract_valid_until'].fillna(2021, inplace=True)
df['team_jersey_number'].fillna(df['nation_jersey_number'], inplace=True)
df.drop(columns=['nation_jersey_number', 'work_rate'], inplace=True)

df.isnull().sum()

player_url                      0
age                             0
height_cm                       0
weight_kg                       0
nationality                     0
club                            0
overall                         0
potential                       0
value_eur                       0
wage_eur                        0
player_positions                0
preferred_foot                  0
international_reputation        0
weak_foot                       0
skill_moves                     0
release_clause_eur              0
team_jersey_number              0
contract_valid_until            0
pace                         2036
shooting                     2036
passing                      2036
dribbling                    2036
defending                    2036
physic                       2036
gk_diving                   16242
gk_handling                 16242
gk_kicking                  16242
gk_reflexes                 16242
gk_speed                    16242
gk_positioning              16242
att_work_rate                   0
def_work_rate                   0
growth                          0
dtype: int64

In [0]:
# explode player_positions into separate rows

df = df.explode('player_positions')
df.head(10)

                                          player_url  age  ...  def_work_rate  growth
0  https://sofifa.com/player/158023/lionel-messi/...   32  ...            Low       0
0  https://sofifa.com/player/158023/lionel-messi/...   32  ...            Low       0
0  https://sofifa.com/player/158023/lionel-messi/...   32  ...            Low       0
1  https://sofifa.com/player/20801/c-ronaldo-dos-...   34  ...            Low       0
1  https://sofifa.com/player/20801/c-ronaldo-dos-...   34  ...            Low       0
2  https://sofifa.com/player/190871/neymar-da-sil...   27  ...         Medium       0
2  https://sofifa.com/player/190871/neymar-da-sil...   27  ...         Medium       0
3  https://sofifa.com/player/200389/jan-oblak/20/...   26  ...         Medium       2
4  https://sofifa.com/player/183277/eden-hazard/2...   28  ...         Medium       0
4  https://sofifa.com/player/183277/eden-hazard/2...   28  ...         Medium       0

[10 rows x 33 columns]

In [0]:
df_gk = df.loc[df['player_positions']=='GK', :]
df_gk = df_gk.drop(columns=['pace', 'shooting','passing','dribbling','defending','physic'])
# df_gk.to_csv('gk.csv', index=False)
df_gk.head(10)

                                           player_url  ...  growth
3   https://sofifa.com/player/200389/jan-oblak/20/...  ...       2
6   https://sofifa.com/player/192448/marc-andre-te...  ...       3
13  https://sofifa.com/player/212831/alisson-ramse...  ...       2
14  https://sofifa.com/player/193080/david-de-gea-...  ...       1
25  https://sofifa.com/player/210257/ederson-santa...  ...       3
28  https://sofifa.com/player/192119/thibaut-court...  ...       1
32  https://sofifa.com/player/167948/hugo-lloris/2...  ...       0
31  https://sofifa.com/player/167495/manuel-neuer/...  ...       0
30  https://sofifa.com/player/162835/samir-handano...  ...       0
53  https://sofifa.com/player/193041/keylor-navas/...  ...       0

[10 rows x 27 columns]

In [0]:
df_outfield = df.loc[df['player_positions']!='GK', :]
df_outfield = df_outfield.drop(columns=['gk_diving', 'gk_handling','gk_kicking','gk_reflexes','gk_speed','gk_positioning'])
# df_outfield.to_csv('outfield_exploded.csv', index=False)
df_outfield.head(10)

                                          player_url  age  ...  def_work_rate  growth
0  https://sofifa.com/player/158023/lionel-messi/...   32  ...            Low       0
0  https://sofifa.com/player/158023/lionel-messi/...   32  ...            Low       0
0  https://sofifa.com/player/158023/lionel-messi/...   32  ...            Low       0
1  https://sofifa.com/player/20801/c-ronaldo-dos-...   34  ...            Low       0
1  https://sofifa.com/player/20801/c-ronaldo-dos-...   34  ...            Low       0
2  https://sofifa.com/player/190871/neymar-da-sil...   27  ...         Medium       0
2  https://sofifa.com/player/190871/neymar-da-sil...   27  ...         Medium       0
4  https://sofifa.com/player/183277/eden-hazard/2...   28  ...         Medium       0
4  https://sofifa.com/player/183277/eden-hazard/2...   28  ...         Medium       0
5  https://sofifa.com/player/192985/kevin-de-bruy...   28  ...           High       0

[10 rows x 27 columns]

In [0]:
targetEncCols = ['nationality', 'club','player_positions','contract_valid_until','att_work_rate','def_work_rate']
ce_targetEncoder = ce.TargetEncoder()

oneHotEncCols = ['preferred_foot']

df_num = df.copy()
df_num[targetEncCols] = ce_targetEncoder.fit_transform(df_num[targetEncCols], df_num['growth'])
df_num = pd.get_dummies(df_num,columns=oneHotEncCols,prefix=oneHotEncCols)
df_num.head(10)

                                          player_url  ...  preferred_foot_Right
0  https://sofifa.com/player/158023/lionel-messi/...  ...                     0
0  https://sofifa.com/player/158023/lionel-messi/...  ...                     0
0  https://sofifa.com/player/158023/lionel-messi/...  ...                     0
1  https://sofifa.com/player/20801/c-ronaldo-dos-...  ...                     1
1  https://sofifa.com/player/20801/c-ronaldo-dos-...  ...                     1
2  https://sofifa.com/player/190871/neymar-da-sil...  ...                     1
2  https://sofifa.com/player/190871/neymar-da-sil...  ...                     1
3  https://sofifa.com/player/200389/jan-oblak/20/...  ...                     1
4  https://sofifa.com/player/183277/eden-hazard/2...  ...                     1
4  https://sofifa.com/player/183277/eden-hazard/2...  ...                     1

[10 rows x 34 columns]

In [0]:
# splitting outfield and goalkeepers

df_gk_num = df_num.loc[df['pace'].isnull(), :]
df_gk_num = df_gk_num.drop(columns=['pace', 'shooting','passing','dribbling','defending','physic','player_url'])
# df_gk.to_csv('gk_num.csv', index=False)
df_gk_num.head(10)

df_outfield_num = df_num.loc[df['gk_diving'].isnull(), :]
df_outfield_num = df_outfield_num.drop(columns=['gk_diving', 'gk_handling','gk_kicking','gk_reflexes','gk_speed','gk_positioning','player_url'])
# df_outfield_num.to_csv('outfield_exploded_num.csv', index=False)
df_outfield_num.head(10)

   age  height_cm  weight_kg  ...  growth  preferred_foot_Left  preferred_foot_Right
0   32        170         72  ...       0                    1                     0
0   32        170         72  ...       0                    1                     0
0   32        170         72  ...       0                    1                     0
1   34        187         83  ...       0                    0                     1
1   34        187         83  ...       0                    0                     1
2   27        175         68  ...       0                    0                     1
2   27        175         68  ...       0                    0                     1
4   28        175         74  ...       0                    0                     1
4   28        175         74  ...       0                    0                     1
5   28        181         70  ...       0                    0                     1

[10 rows x 27 columns]

In [0]:
# function to scale and plot corr matrix
def standard_scale(dataset):
    df = dataset.copy(deep=True)   
    data = df.values
    scaler = StandardScaler()
    scaler.fit(data)
    data_scaled = scaler.transform(data)
    df = pd.DataFrame(data_scaled)
    df.columns = dataset.columns
    return df


def plot_corr_matrix(dataset):
    df = dataset.copy(deep=True)
    
    # scale data
    data = df.values
    scaler = StandardScaler()
    scaler.fit(data)
    data_scaled = scaler.transform(data)
    df = pd.DataFrame(data_scaled)

    # calculate correlation matrix
    corr = df.corr()
    corr.style.background_gradient(cmap='coolwarm').set_precision(2)
    fig, ax = plt.subplots(figsize=(df.columns.size, df.columns.size))
    ax.matshow(corr)
    plt.xticks(range(len(corr.columns)), dataset.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), dataset.columns)
    plt.savefig('plot_scaled.png')
    plt.show()

In [0]:
plot_corr_matrix(df_outfield_num)

In [0]:
outfield_corr = df_outfield_num.corr()
outfield_corr.head(10)

                       age  ...  preferred_foot_Right
age               1.000000  ...              0.007642
height_cm         0.039774  ...              0.040167
weight_kg         0.197070  ...              0.043445
nationality      -0.230625  ...              0.016400
club             -0.332433  ...             -0.001378
overall           0.430000  ...             -0.016904
potential        -0.304703  ...             -0.019315
value_eur         0.075110  ...             -0.008954
wage_eur          0.143547  ...             -0.010912
player_positions -0.073835  ...              0.014076

[10 rows x 27 columns]

In [0]:
df_outfield_norm = standard_scale(df_outfield_num)
outfield_norm_corr = df_outfield_norm.corr()
outfield_norm_corr.head(10)

                       age  ...  preferred_foot_Right
age               1.000000  ...              0.007642
height_cm         0.039774  ...              0.040167
weight_kg         0.197070  ...              0.043445
nationality      -0.230625  ...              0.016400
club             -0.332433  ...             -0.001378
overall           0.430000  ...             -0.016904
potential        -0.304703  ...             -0.019315
value_eur         0.075110  ...             -0.008954
wage_eur          0.143547  ...             -0.010912
player_positions -0.073835  ...              0.014076

[10 rows x 27 columns]

In [0]:
gk_corr = df_gk_num.corr()
gk_corr.to_csv('gk_corr.csv', index=False)